apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginxapps
  namespace: default
  labels:
    app:  nginxapps
spec:
  selector:
    matchLabels:
      app: nginxapps
  replicas: 10

  template:
    metadata:
      labels:
        app: nginxapps
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  nginxapps
        image: 11122233345/dotnetwebapptraining
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi       
        
        ports:
        - containerPort:  80
          name:  nginxport  
      restartPolicy: Always